components:
  aub_configs:
    branch: aub_configs
    dest_dir: aub_configs
    revision: b08d1653ff1f44a0c0e3da37cf57ab789b132a32
    type: git
  aub_stream:
    branch: master
    dest_dir: aub_stream
    repository: https://github.com/intel/aubstream
    revision: b5abbe0564dcad9e225799c5c6c1c06a21b59fd4
    type: git
  gmmlib:
    asset_name: gmmlib
    branch: master
    dest_dir: gmmlib
    repository: https://github.com/intel/gmmlib.git
    revision: intel-gmmlib-22.7.0
    type: git
  igc:
    asset_name: igc
    branch: releases/2.11.x
    dest_dir: igc
    repository: https://github.com/intel/intelgraphicscompiler
    revision: d88c4f68a13f63dc0341f9f01fb1e63160592e58
    type: git
  igsc:
    asset_name: igsc
    branch: master
    component_version: 301
    dest_dir: igsc
    repository: https://github.com/intel/igsc.git
    revision: V0.9.5
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: FETCH_HEAD
    type: git
  kernels_bin:
    branch: kernels_bin
    dest_dir: kernels_bin
    revision: 3406-4167
    type: git
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: e73be7d107f5c18e8e2260da962239b33b7293ec
    type: git
  level_zero:
    asset_name: level_zero
    branch: master
    dest_dir: level_zero
    repository: https://github.com/oneapi-src/level-zero
    revision: v1.21.9
    type: git
  libva:
    asset_name: libva
    branch: v2.2-branch
    dest_dir: libva
    repository: https://github.com/intel/libva.git
    revision: 2.2.0
    type: git
  metrics-discovery:
    asset_name: metrics-discovery
    branch: master
    dest_dir: metrics/discovery
    repository: https://github.com/intel/metrics-discovery.git
    revision: metrics-discovery-1.14.180
    type: git
  metrics-library:
    asset_name: metrics-library
    branch: master
    dest_dir: metrics/library
    repository: https://github.com/intel/metrics-library.git
    revision: metrics-library-1.0.196
    type: git
  neo-clang-format:
    branch: clang-format
    dest_dir: tools/clang-format
    revision: 15.0.6
    type: git
  wdk:
    branch: wdk
    dest_dir: wdk
    revision: 97f389b0607d40ce6096b9a22c113f79d609207e-3393
    type: git
  wsl:
    branch: wsl
    dest_dir: wsl
    revision: 56430997dac34ca0e9e18c177636234cac26ad54
    type: git
converter: M-3406
include:
- infra.yml
version: '1'
